build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"

install:
  - "%PYTHON%\\python.exe -m pip install six"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

test_script:
  - "%PYTHON%\\python.exe t/test.py"
